if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

    Plug 'tpope/vim-sensible'
    Plug 'preservim/nerdtree'
"    Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

